version: "3"
services:
  # メインのWeb開発サービス（コンテナ）
  dev:
    # Dockerfileをビルドしてイメージを作成する設定
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      # このファイルから1階層上のディレクトリを、コンテナ内の /workspace ディレクトリにマウント
      # (/workspace がVisual Studio Codeが開くディレクトリとなる）
      - ..:/workspace:cached
      - root_node_modules:/workspace/node_modules
      - pnpm_store:/workspace/.pnpm-store

    # コンテナが自動終了しないようにする
    command: sleep infinity

  # DBサービス（コンテナ）
  # from <https://github.com/devcontainers/templates/tree/main/src/javascript-node-postgres>
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  # DB管理ツールAdminerをインストールするサービス（コンテナ）
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_DB_DRIVER: postgres

volumes:
  # 名前付きボリュームを定義
  root_node_modules:
  pnpm_store:
  postgres-data:
