version: "3"
services:
  # メインのWeb開発サービス（コンテナ）
  dev:
    # Dockerfileをビルドしてイメージを作成する設定
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      # このファイルから1階層上のディレクトリを、コンテナ内の /workspace ディレクトリにマウント
      # (/workspace がVisual Studio Codeが開くディレクトリとなる）
      - ..:/workspace:cached
      - root_node_modules:/workspace/node_modules
      - pnpm_store:/workspace/.pnpm-store
      - nuxt:/workspace/.nuxt

    # コンテナが自動終了しないようにする
    command: sleep infinity

    # 環境変数
    environment:
      # DevcontainerでもNuxt.jsのHot Reloadを有効にする
      # from <https://www.ikkitang1211.site/entry/2020/10/11/213824>
      CHOKIDAR_USEPOLLING: true

      # 全IPアドレスで公開するように設定（Nuxt.jsなどの開発時に必要）
      HOST: 0.0.0.0

      # Nuxt.jsで使用するポート番号を指定
      PORT: 45672

      # DB接続設定（Prismaで使用）
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres?schema=public"

  # DBサービス（コンテナ）
  # from <https://github.com/devcontainers/templates/tree/main/src/javascript-node-postgres>
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  # DB管理ツールAdminerをインストールするサービス（コンテナ）
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DESIGN: hever

volumes:
  # 名前付きボリュームを定義
  root_node_modules:
  pnpm_store:
  nuxt:
  postgres-data:
